OpenTechStrategies/lisc-ttm

- INSTALL.md
- robots.txt
Reviewed with @kfogel and we will do the necessary thing on the servers.
> Issue 28 make a robots.txt file

- enlace/ajax/create_program.php
- enlace/ajax/new_inst.php
- enlace/ajax/save_progsurv.php
- enlace/ajax/search_participants.php
- enlace/campaigns/campaign_profile.php
- enlace/events/events.php
- enlace/participants/participant_profile.php
- enlace/programs/new_program_survey.php
This was causing some issues with some installs of php5.
> Change <? to <?php

- enlace/ajax/search_participants.php
- enlace/programs/profile.php
Only used in the program page for now.
Just added a verbose flag to the dropdown generation options.
> Fix #190. Add participant search verbose setting.

- enlace/programs/profile.php
- styles/styles.css
@cecilia-donnelly For your review
This is in the programs page, when looking at attendance sheets that have yet to be filled out.
> Fix #203. Make no attendance rows yellow

- enlace/participants/participants.php
@cecilia-donnelly For your review
UI change only for data entry users.  Still want all the permissions to be the same on the back end because other parts of the interface continue to allow new participants to be entered.
> Fix #198.  Add an admin check for Add Participants

- enlace/include/dosage_percentage.php
@cecilia-donnelly for your review.
New calculations use the attendance model added as a fix for #192, wherein it's based on attendance vs absence without taking into account unrecorded sessions.  Easiest way to see the change is to auto generate a session and then mark attendance for only one of the dates.
We also talked about this in PR #197
> Fix #199. Change dosage calculations.

- enlace/ajax/add_participant.php
- enlace/participants/participants.php
- enlace/programs/profile.php
@cecilia-donnelly For your review
There's a server side component that should be challenging to execute unless you turn javascript off, but then the ajax call won't work.  It should never be executed without someone trying to circumvent the client side checking code, which would be odd in a private system.
Note: The whitespace change in participants.php is so that there isn't a crazy merge conflict after #198 is merged.  If you'd rather clear that one and have me rebase after I merge so that this diff is cleaner, that's cool.
> Fix #200. Add checking for mandatory demographics.

- enlace/reports/num_programs.php
- styles/styles.css
@cecilia-donnelly for your review.
This adds a popup box to the program enrollment report that allows you to select programs.  In order to get any kind of results, you need to select December 2015 for the month/year (though that will be fixed with #206).
> Fix #204.  Add a program selection to enrollment.

- enlace/reports/num_programs.php
@cecilia-donnelly for your review.
This one can be tested similarly to #204, in the program report.  For a session to be included, both the start and end date need to fall between the date range (and it's optional to leave one of the start or end empty), and then the count is for that session, regardless of when the participant joined.
> Fix #206.  Use Dates for Program Enrollment Report

- enlace/reports/attendance.php
@cecilia-donnelly A one liner.  I'm not sure where this broke, and why it's not in production, but I do know it was fixed by this change.  Most likely caused by the work I did to the dosage reports.
> Fix weird issue where connection getting closed.

- enlace/events/events.php
- enlace/institutions/institutions.php
- enlace/programs/new_program_survey.php
@cecilia-donnelly This was done earlier as #189, but I missed a few files because of a malformed grep, and I'll auto merge tomorrow if you don't have a chance to look at it today (or punt to @kfogel since he merged the last one)
> Change <? to <?php part two, missed one

- enlace/include/dosage_percentage.php
- enlace/reports/attendance.php
- include/generalized_download_script.php
Issue #220 
Test by looking at attendance report and seeing missing attendances in yellow.
(Merge against 218, because I built each branch on the one before it to save time)
> Enlace: Identify Missing Attendance

- enlace/reports/assessments.php
- enlace/reports/attendance.php
Add the program selects to the assessment and attendance reports.
Test by looking at the assessment and attendance reports, and confirming that they use the new program select boxes.
> Issue #241 Enlace: Update program selects

- enlace/ajax/save_assessments.php
- enlace/participants/all_impact.php
- enlace/participants/all_intake.php
Issue #225: Enlace: Force survey administer date to be within a given time window of current date
Test by logging in as a data entry user and attempting to set a survey date to greater than 2 months in the past.
> Fix #225: Enlace: Force survey date recent

- enlace/ajax/save_assessments.php
- enlace/include/attendance.php
- enlace/participants/all_impact.php
- enlace/participants/all_intake.php
Issue #228.
Test by logging in as admin and seeing that you can:
* Set survey administer date with impunity
* Edit completed surveys
* Edit any attendance
> Remove restrictions for admins

- enlace/programs/profile.php
Issue #242: Enlace: Program profile page is slow when lots of session
Issue #218: Enlace: Hiding past data
Only queries for sessions within the recent session window, as opposed to before where it only hid them in the UI.
Test by going through UI for viewing old programs, and new ones.
> Fix #242: Enlace: Program Page Slowness

- enlace/reports/assessments.php
Test by looking at assessment report, and seeing number of surveys reported.
> Fix #234: Add number of surveys to assmt report.

- enlace/reports/assessments.php
Test by playing with date range in the survey reports.
> Fix #202.  Include a date range for Survey Reports

- enlace/programs/attendance_report.php
- enlace/programs/profile.php
- enlace/programs/upload_attendance_report.php
- styles/styles.css
Test by downloading and uploading attendance csvs.
> Fix #239: Add attendance csv upload

- enlace/ajax/edit_program.php
- enlace/header.php
- enlace/institutions/inst_profile.php
- enlace/institutions/institutions.php
- enlace/participants/participant_profile.php
- enlace/programs/profile.php
- enlace/programs/programs.php
- enlace/reports/attendance.php
- enlace/reports/num_programs.php
- enlace/reports/production_exports.php
- include/generalized_download_script.php
This does not change the underlying database/code as that effort would be huge and we should make sure that we are sticking with these before we do that.
Issue #251: Change key words to represent new usage
Test by looking at the various pages and seeing the new words
> Change UI names of core words.

- enlace/programs/attendance_report.php
The production server is woefully out of date, and this function is not available.
Issue #239: TTM read and process CSV files of attendance data
> Stop using mysqli_fetch_all
